name: flutter_secure_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  crypto: ^3.0.6
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  intl: ^0.20.2
  mockito: ^5.4.6
  build_runner: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
