// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlc4QTXCm6pO5qUNpbDdMDmhBFupfWy0',
    appId: '1:902440876555:web:ef52f393dc5e98f43ce50e',
    messagingSenderId: '902440876555',
    projectId: 'chat-8b923',
    authDomain: 'chat-8b923.firebaseapp.com',
    storageBucket: 'chat-8b923.firebasestorage.app',
    measurementId: 'G-S946PS2KHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa4P4plZ1H1tJtdX__Fa3E01mS7WBEcG0',
    appId: '1:902440876555:android:1863b91a587ec0d63ce50e',
    messagingSenderId: '902440876555',
    projectId: 'chat-8b923',
    storageBucket: 'chat-8b923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfZpKF64IZEEgkHsEGIEYs4xDsH-4MsE',
    appId: '1:902440876555:ios:bc34ae4bf59031bd3ce50e',
    messagingSenderId: '902440876555',
    projectId: 'chat-8b923',
    storageBucket: 'chat-8b923.firebasestorage.app',
    iosBundleId: 'com.example.flutterSecureChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZfZpKF64IZEEgkHsEGIEYs4xDsH-4MsE',
    appId: '1:902440876555:ios:bc34ae4bf59031bd3ce50e',
    messagingSenderId: '902440876555',
    projectId: 'chat-8b923',
    storageBucket: 'chat-8b923.firebasestorage.app',
    iosBundleId: 'com.example.flutterSecureChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlc4QTXCm6pO5qUNpbDdMDmhBFupfWy0',
    appId: '1:902440876555:web:eb236f3b5aa78fa93ce50e',
    messagingSenderId: '902440876555',
    projectId: 'chat-8b923',
    authDomain: 'chat-8b923.firebaseapp.com',
    storageBucket: 'chat-8b923.firebasestorage.app',
    measurementId: 'G-T6XEF0ZB8H',
  );

}